# Generated by Django 5.2.6 on 2026-04-15 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('standard_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rush_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requirements', models.TextField(help_text='List of requirements needed for this document')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('urgency_level', models.CharField(choices=[('STANDARD', 'Standard'), ('RUSH', 'Rush')], default='STANDARD', max_length=10)),
                ('purpose_of_request', models.TextField()),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transactions_app.document')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to='core_app.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('proof_of_payment', models.ImageField(upload_to='payments/proofs/')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='core_app.staff')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='transactions_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('PICKUP', 'Pick-up'), ('COURIER', 'Courier Delivery')], max_length=15)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('courier_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('date_claimed', models.DateField(blank=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_details', to='transactions_app.request')),
            ],
        ),
    ]
